<?php
_time_elapsed('bootstrap 1');

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

$configurator->onCompile[] = function ($configurator, $compiler) {
    $compiler->addExtension('ajax', new VojtechDobes\NetteAjax\Extension);
};

use Nette\Application\Routers\RouteList,
    Nette\Application\Routers\Route;

//$router = new RouteList;
//$router[] = new Route('<presenter>/[<action>/]', 'List:default');

//$container->addService('router', $router);
$container->router[] = new Route('<presenter>/[<action>/]', 'List:default');

return $container;



function _time_elapsed($text = "")
{
    static $last = null;

    $now = microtime(true);

    if ($last != null) {
        dump($text.' - '.($now - $last));
    }

    $last = $now;
}